stages:
  - lint
  - build
  # - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

lint:
  image: yangm97/luacheck
  stage: lint
  script:
    - luacheck .

build:
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - staging
    - production

deploy:
  stage: deploy
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker stack deploy $CI_COMMIT_REF_SLUG -c docker-compose.yml
  only:
    - staging
    - production
