version: '3.3'

services:
  groupbutler:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: on-failure
    volumes:
      - ./conf:/srv/app/conf
      - ./locales:/srv/app/locales
      - ./lua:/srv/app/lua
      - ./polling.lua:/srv/app/polling.lua

  redis:
    command: --save "" --appendonly no
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"
