version: '3.6'

services:
  groupbutler:
    build:
      context: .
      dockerfile: webhooks.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./conf:/usr/local/openresty/nginx/conf
      - ./locales:/usr/local/openresty/nginx/locales
      - ./lua:/usr/local/openresty/nginx/lua
